### ISSUE TITLE
The settings `testDirectoryName` and `testFileExtensions` were removed from Jest

### ISSUE THREAD

**Issue by rafalschmidt97** [iroy2000/react-redux-boilerplate#1]
Hi!
**node v6.8.1
npm  v4.0.0
system: MacOs El Capitan**

What i only did:
- unpacked your project
- run: npm install
- run: npm run dev

Did I make somewhere mistake  or did not install something?
Your project looks great

```
> retro-community@0.5.0 test /Users/rafalschmidt/Downloads/react-redux-boilerplate-master
> jest --verbose

● The `unmockedModulePathPatterns` setting is defined but automocking is disabled in Jest. Please either remove `unmockedModulePathPatterns` from your configuration or expl
icitly set `"automock": true` in your configuration if you wish to use automocking.

  Jest 15 changed the default configuration for tests and makes Jest easier to
  use and less confusing for beginners. All previous defaults can be restored
  if your project depends on it. A comprehensive explanation of the breaking
  changes and an upgrade guide can be found in the release blog post linked
  below.

  Jest Issue Tracker: https://github.com/facebook/jest/issues
  Configuration Documentation: https://facebook.github.io/jest/docs/configuration.html
  Release Blog Post: https://facebook.github.io/jest/blog/2016/09/01/jest-15.html


Error: The settings `testDirectoryName` and `testFileExtensions` were removed from Jest. Instead, use `testRegex` like this:
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(js|jsx|json)$"

  Jest 15 changed the default configuration for tests and makes Jest easier to
  use and less confusing for beginners. All previous defaults can be restored
  if your project depends on it. A comprehensive explanation of the breaking
  changes and an upgrade guide can be found in the release blog post linked
  below.

  Jest Issue Tracker: https://github.com/facebook/jest/issues
  Configuration Documentation: https://facebook.github.io/jest/docs/configuration.html
  Release Blog Post: https://facebook.github.io/jest/blog/2016/09/01/jest-15.html

    at throwConfigurationError (/Users/rafalschmidt/Downloads/react-redux-boilerplate-master/node_modules/jest-config/build/normalize.js:36:9)
    at normalize (/Users/rafalschmidt/Downloads/react-redux-boilerplate-master/node_modules/jest-config/build/normalize.js:226:11)
    at promisify.then (/Users/rafalschmidt/Downloads/react-redux-boilerplate-master/node_modules/jest-config/build/loadFromPackage.js:24:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v6.8.1
npm ERR! npm  v4.0.0
npm ERR! code ELIFECYCLE
npm ERR! retro-community@0.5.0 test: `jest --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the retro-community@0.5.0 test script 'jest --verbose'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the retro-community package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest --verbose
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs retro-community
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls retro-community
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rafalschmidt/Downloads/react-redux-boilerplate-master/npm-debug.log
```

**Comment by iroy2000** [comment]
@rshmiraf  Thanks for the issue, let me look into that.

**Comment by iroy2000** [comment]
@rshmiraf That issue is fixed, please update your repo and try again ? Thanks for reporting :)

![jest_issue_fixed](https://cloud.githubusercontent.com/assets/487520/19778192/68e9d898-9c30-11e6-806d-6f370ea37911.png)

Closing this now.

**Comment by rafalschmidt97** [comment]
@iroy2000 Great! Now it's fine :) What I only need to do it's just add sass and react-bootstrap! Thanks a lot. This is exactly what I looking for (boilerplate like this)

**Comment by iroy2000** [comment]
@rshmiraf Glad it helps.

Btw, this boilerplate includes PostCSS with post css nested plugin, which you can do similar thing to sass.  But it is up to personal favorite.
